### ISSUE TITLE
Local stats on items are not handled correctly

### ISSUE THREAD

**Issue by 766b** [Kyusung4698/PoE-Overlay#32]
Here are two examples.

If `Adds 30 to 52 Physical Damage` is selected then there will be no results from search. Issue is that it's added as `pseudo` instead of `Local`. Because it's a physical weapon, stat is added locally unto itself, if the same stat is found on gloves for example, then it's a global modifier (then it can be added as `explicit`).

Second case, is pretty much the same. `68% increased Armour` is a `local` modifier on an armor piece. If it was amulet with `#% increased Armour`, then it can be added as `explicit`

From my last look at source code, for now it appears we just matching strings with whatever comes first, which was the reason for issue #24 since there are several stats entries that look the same, but are intended for different things.

Take a look `https://www.pathofexile.com/api/trade/data/stats`, there are only 18 entries that are explicit `(Local)` and they are either for armor (armor, es, evasion) or weapon (flat, ele, acc, poison) modifiers. So it probably would be better to look for entries ending in `(Local)` for weapons and armors. Same applies to `crafted`, `fractured` and `implicit`s types.

PS: This is probably only applicable to rares, not sure about uniques.
~~~

Rarity: Rare
Damnation Song
Imperial Bow
--------
Bow
Physical Damage: 144-381 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.45
--------
Requirements:
Level: 66
Dex: 212 (unmet)
--------
Sockets: R-R R G 
--------
Item Level: 75
--------
20% increased Elemental Damage with Attack Skills (implicit)
--------
+38 to Dexterity
193% increased Physical Damage
Adds 30 to 52 Physical Damage
Gain 10% of Physical Damage as Extra Chaos Damage
+27 to Accuracy Rating`

===========================

Rarity: Rare
Damnation March
Titan Greaves
--------
Armour: 405 (augmented)
--------
Requirements:
Level: 68
Str: 120
--------
Sockets: R 
--------
Item Level: 71
--------
68% increased Armour
Regenerate 3 Life per second
+7% to Cold Resistance
+41% to Lightning Resistance
30% increased Movement Speed

**Comment by pj4533** [comment]
Not sure if this is the same bug, but here the mana leech doesn't show up:

Rarity: Rare
Sol Goad
Imbued Wand
--------
Wand
Physical Damage: 48-93 (augmented)
Critical Strike Chance: 7.00%
Attacks per Second: 1.50
--------
Requirements:
Level: 59
Int: 188
--------
Sockets: B-B B 
--------
Item Level: 82
--------
34% increased Spell Damage (implicit)
--------
33% increased Physical Damage
Adds 8 to 17 Physical Damage
4% increased Fire Damage
0.29% of Physical Attack Damage Leeched as Mana
+55 to Accuracy Rating

**Comment by 766b** [comment]
It's not the same issue, but a bug none the less, probably warrants it's own issue. Looks like while parsing script is only looking for whole numbers, and then it fails to find anything then whole line is omitted. 

That's actually two issues,
1. Decimals are not handled correctly
2. If parser for a line yield no results then it's silently omitted without any feedback.

**Comment by pj4533** [comment]
Did the original bug here get fixed in 0.5.0?   i have run into it a few times, and always have to show the browser window, click the mod, and select the 'local' version manually.

**Comment by pj4533** [comment]
Can confirm I am still seeing it in 0.5.0, so guess not.

**Comment by Kyusung4698** [comment]
> Can confirm I am still seeing it in 0.5.0, so guess not.

Should now work with 0.5.1. Please report back 👍

**Comment by pj4533** [comment]
Hmmmm..... still seeing it in 0.5.1     For example:

```
Rarity: Rare
Onslaught Grip
Sorcerer Gloves
--------
Energy Shield: 150 (augmented)
--------
Requirements:
Level: 69
Int: 97
--------
Sockets: B-B-B-G 
--------
Item Level: 84
--------
+249 to Accuracy Rating
+35 to maximum Energy Shield
83% increased Energy Shield
+70 to maximum Mana
```

The maximum energy shield mod required me to manually select the 'local' version in the web browser.

**Comment by Kyusung4698** [comment]
> The maximum energy shield mod required me to manually select the 'local' version in the web browser.

I see. Thanks for your feedback. Seems like I missed some. I'll investigate.

**Comment by pj4533** [comment]
No problem, happy to help.  You are doing fantastic work with this tool, the way you have taken on the goal of integrating it into the UI (rather than an ugly popup), is truely amazing.   Keep it up!!!

**Comment by Kyusung4698** [comment]
> No problem, happy to help. You are doing fantastic work with this tool, the way you have taken on the goal of integrating it into the UI (rather than an ugly popup), is truely amazing. Keep it up!!!

Thanks for your feedback. This issue has been addressed with version 0.5.2. Please report back 👍

**Comment by Kyusung4698** [comment]
I'll close this for now. Please open an new issue if there are still local mods missing. Thanks!
