### ISSUE TITLE
focus/layer problems

### ISSUE THREAD

**Issue by SchmutzigerStefan** [Kyusung4698/PoE-Overlay#608]
so i know this was mentioned before, but since there was a fix twice yesterday and i still have massive problems. So as soon as i try to evaluate any item or do a map check, nothing happens. The version number bottom left disappears and i have to tab out of the game to actually see the overlay. So i guess the overlay just spawns behind the game as soon as i try to perform any action.
I cant fix this, tried reinstalling, disabling almost any other porgrams etc.
Sadly its unusable right now for me :(
Anyone still has this problems too?

**Comment by ewolz3** [comment]
I can confirm I still have this bug today. Was hoping the update yesterday would fix it.

**Comment by Diab0lic** [comment]
same here, using 0.6.17, latest stable version for me.

**Comment by KurtWerner2020** [comment]
same here, using 0.6.17 as well, works great so far.

**Comment by kubicka** [comment]
Same here, but 0.6.17 is not working for me either have to use 0.6.16

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I've released a [pre-release of version 0.6.21](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/v0.6.21) which should fix this issue. As it's marked as pre-release you'd need to install it manually. Please let me know if everything works and i'll remove the pre-release tag. Thanks!

**Comment by ewolz3** [comment]
@Kyusung4698 

Tested for an hour or so, seems to have fixed the issue with the overlay itself. One thing that is still an issue is the right click menu from the task bar isn't focused. Please see screenshot. 
![layers](https://user-images.githubusercontent.com/26370663/79077741-9818e980-7cd1-11ea-923b-aeaf9f020144.png)

**Comment by Kyusung4698** [comment]
> @Kyusung4698
> 
> Tested for an hour or so, seems to have fixed the issue with the overlay itself. One thing that is still an issue is the right click menu from the task bar isn't focused. Please see screenshot.
> ![layers](https://user-images.githubusercontent.com/26370663/79077741-9818e980-7cd1-11ea-923b-aeaf9f020144.png)

@ewolz3 alright! Thanks for your feedback. I've removed the pre-release tag. The tray menu issue is a known Electron bug and unfortunately there is no solution for this for now. A quick workaround is multiple right clicks. This may move the tray menu up. See following issue for more #591

**Comment by Kyusung4698** [comment]
## 0.6.21 (2020-04-12)

- fix move poe overlay to top after focusing poe (#608)
